### ISSUE TITLE
Sound does not work inside the container

### ISSUE THREAD

**Issue by AlxCzl** [PentHertz/RF-Swift#3]
## Problem

The container cannot output sound in a lot of programs, some of which cannot even launch because of this (i.e gqrx).

## Potential fix

Exporting the following environment variable inside the container:
```sh
export PULSE_SERVER=unix:/run/user/1000/pulse/native
```
And launching `rfswift` with `-b "/run/user/1000/pulse:/run/user/1000/pulse"`.

Notice the `1000` in the previous comments: this has to be adapted to the current user ID.
This can be done either in the compilation, or by passing arguments to the docker commands used by `rfswift`.
I suggest using the second solution, as it will be more flexible than the first.
I'll try to send a PR when I can.

**Comment by FlUxIuS** [comment]
Thank you Alexandre!

Maybe we should use pulseaudio TCP to simplify accesses from Windows, macOS, and Linux as suggested here: https://github.com/PentHertz/RF-Swift?tab=readme-ov-file#sound

Relying to a TCP port would maybe a good option. What do you think?

**Comment by FlUxIuS** [comment]
There are good points, but assuming people are using Windows or macOS, they will have to install **pulseaudio** anyway. We can handle commands on the host with RF Swift + Container so for Linux integrating your solution on binded sock or TCP one will be invisible to the users. But for Windows and macOS, they will have to install at least **pulseaudio** and use TCP. So maybe the most preferred way to support them all is to use TCP I think.

**Comment by FlUxIuS** [comment]
Hey,

The issue was normally solved using your proposition, but on TCP https://github.com/PentHertz/RF-Swift/commit/80def558b789974a58eff7a53ab360a6ec682093.

Can you check if that works OK for you, so we can close this issue?

Thanks in advance! ;)

**Comment by AlxCzl** [comment]
Hey, sorry didn't have the time to look at the updates.
Well, you seem focused on the TCP fix, I'll try it then and report back in a few.

**Comment by FlUxIuS** [comment]
Since version v0.4.3, it's possible to enable and unload pulse audio TCP through RF Swift like that: 

```
Manage pulseaudio server

Usage:
  rfswift host audio [command]

Available Commands:
  enable      Enable connection
  unload      Unload TCP module from Pulseaudio server
```
