### ISSUE TITLE
Terminal behavior is broken inside the container

### ISSUE THREAD

**Issue by AlxCzl** [PentHertz/RF-Swift#4]
## Problem

I cannot use arrows, ctrl+arrows, ctrl+d and more inside the container.

Here are a few examples:

- left arrow
```sh
Version:0.1

non-network local connections being added to access control list

root@tyk0machine:~# this is a test^[[D
```

- ctrl+r (no prompt, apparently works correctly in the background)
```sh
Version:0.1

non-network local connections being added to access control list

root@tyk0machine:~# ^R
tesrtsdgdsf
tesrtsdgdsf
bash: tesrtsdgdsf: command not found
root@tyk0machine:~# 
```

- ctrl+d has no effect
- ctrl+c kills the terminal

## Fix

None at the moment. I guess that this has to do with the fact that we are dropped in a shell from program. Might be a problem with io redirections.

**Comment by FlUxIuS** [comment]
Hello @AlxCzl,

Use version V0.2 or 0.3 that solves the issue. V0.1's terminal was experimental and broken. 

You can build the new version using the `build.sh` or grab it from: https://github.com/PentHertz/RF-Swift/releases/tag/v0.3-pre

Don't hesitate if you see something else broken ;)
