### ISSUE TITLE
Osmo-nitb-scripts Tool Addition

### ISSUE THREAD

**Issue by Ali6114** [PentHertz/RF-Swift#6]
Please add the Osmocom NITB scripts with osmocom stack to the telecom tag tools. It would be great to include the Osmocom alongside other tools like OpenBTS in the telecom tag.

https://github.com/notpike/osmo-nitb-scripts

**Comment by FlUxIuS** [comment]
Osmocom Telco tools are now integrated: https://github.com/PentHertz/RF-Swift/commit/fb00ae8a36f7f1f58f32878f9247bd061df935de

We can maybe also integrate the scripts, but those scripts will have to be readapted for the architecture of RF Swift.

**Comment by FlUxIuS** [comment]
That is a todo list to script in https://github.com/PentHertz/RF-Swift-images
